worker_processes auto;

events {}

http {
  include /etc/nginx/mime.types;
  keepalive_timeout 65;

  server {
    listen 80;
    server_name localhost;

      location / {
      root /usr/share/nginx/html;
      index index.html;
      try_files $uri $uri/ /index.html;

      location /api {
        proxy_pass https://api.github.com/graphql;
      }

      location /img/ {
        alias /usr/share/nginx/html/image/;
      }

      location /json {
        default_type application/json;

        add_header Content-Type application/json;
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        add_header Pragma "no-cache";
        add_header Expires "0";
      
        return 200 '{"status": "ok", "message": "This is a JSON response from Nginx."}';
      }
    }
  }
}